UPDATE public.categories
SET "categorySector" = CASE "categoryName"
    WHEN '디지털/가전' THEN '디지털/가전'::"CategorySectors"
    WHEN '가구/홈' THEN '홈 데코'::"CategorySectors"
    WHEN '자동차' THEN '자동차/취미'::"CategorySectors"
    WHEN '스포츠/레저' THEN '자동차/취미'::"CategorySectors"
    WHEN '의류/잡화' THEN '의류/잡화'::"CategorySectors"
    WHEN '침구/패브릭' THEN '홈 데코'::"CategorySectors"
    WHEN '생활용품' THEN '생활용품'::"CategorySectors"
    WHEN '세제/청소용품' THEN '생활용품'::"CategorySectors"
    WHEN '주방' THEN '생활용품'::"CategorySectors"
    WHEN '문구/사무용품' THEN '문구/사무/아동/반려'::"CategorySectors"
    WHEN '아동' THEN '문구/사무/아동/반려'::"CategorySectors"
    WHEN '미용' THEN '건강/미용'::"CategorySectors"
    WHEN '건강' THEN '건강/미용'::"CategorySectors"
    WHEN '반려동물' THEN '문구/사무/아동/반려'::"CategorySectors"
    WHEN '액세서리' THEN '의류/잡화'::"CategorySectors"
    WHEN '럭셔리' THEN '의류/잡화'::"CategorySectors"
    WHEN '패션잡화' THEN '의류/잡화'::"CategorySectors"
    WHEN '냉장/냉동' THEN '냉장/냉동/가공식품'::"CategorySectors"
    WHEN '육류' THEN '신선식품'::"CategorySectors"
    WHEN '해산물' THEN '신선식품'::"CategorySectors"
    WHEN '농산물' THEN '신선식품'::"CategorySectors"
    WHEN '과일' THEN '신선식품'::"CategorySectors"
    WHEN '식재료' THEN '식자재'::"CategorySectors"
    WHEN '소스/양념' THEN '식자재'::"CategorySectors"
    WHEN '즉석식품' THEN '즉석식품/간식'::"CategorySectors"
    WHEN '빵' THEN '즉석식품/간식'::"CategorySectors"
    WHEN '과자/간식' THEN '즉석식품/간식'::"CategorySectors"
    WHEN '커피/차' THEN '즉석식품/간식'::"CategorySectors"
    WHEN '주류' THEN '주류/음료'::"CategorySectors"
    WHEN '음료' THEN '주류/음료'::"CategorySectors"
    WHEN '가공식품' THEN '냉장/냉동/가공식품'::"CategorySectors"
    ELSE '기타'::"CategorySectors"
END;
