create table "public"."dalins" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "category_name" text,
    "from_date" text,
    "product_image" text,
    "product_name" text,
    "discount" integer,
    "sale_price" integer,
    "category_image" text,
    "category_id" smallint,
    "normal_price" integer,
    "to_date" text,
    "product_id" integer,
    "discount_condition" text
);


CREATE UNIQUE INDEX dalin_pkey ON public.dalins USING btree (id);

alter table "public"."dalins" add constraint "dalin_pkey" PRIMARY KEY using index "dalin_pkey";

grant delete on table "public"."dalins" to "anon";

grant insert on table "public"."dalins" to "anon";

grant references on table "public"."dalins" to "anon";

grant select on table "public"."dalins" to "anon";

grant trigger on table "public"."dalins" to "anon";

grant truncate on table "public"."dalins" to "anon";

grant update on table "public"."dalins" to "anon";

grant delete on table "public"."dalins" to "authenticated";

grant insert on table "public"."dalins" to "authenticated";

grant references on table "public"."dalins" to "authenticated";

grant select on table "public"."dalins" to "authenticated";

grant trigger on table "public"."dalins" to "authenticated";

grant truncate on table "public"."dalins" to "authenticated";

grant update on table "public"."dalins" to "authenticated";

grant delete on table "public"."dalins" to "service_role";

grant insert on table "public"."dalins" to "service_role";

grant references on table "public"."dalins" to "service_role";

grant select on table "public"."dalins" to "service_role";

grant trigger on table "public"."dalins" to "service_role";

grant truncate on table "public"."dalins" to "service_role";

grant update on table "public"."dalins" to "service_role";


