drop function if exists "public"."get_discounts_with_wishlist_counts"(_current_time_stamp timestamp without time zone, _user_id uuid, _category_sector "CategorySectors");

create table "public"."histories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "new_item_count" integer,
    "added_discount_count" integer,
    "no_images" text[]
);


alter table "public"."items" add column "bestDiscount" numeric;

CREATE UNIQUE INDEX history_pkey ON public.histories USING btree (id);

alter table "public"."histories" add constraint "history_pkey" PRIMARY KEY using index "history_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_discounts_with_wishlist_counts(_current_time_stamp timestamp without time zone, _user_id uuid, _category_sector "CategorySectors")
 RETURNS TABLE(id integer, "startDate" timestamp without time zone, "endDate" timestamp without time zone, price numeric, "discountPrice" numeric, "discountRate" numeric, discount numeric, items jsonb)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY EXECUTE
    'SELECT
        d.id,
        d."startDate",
        d."endDate",
        d.price,
        d."discountPrice",
        d."discountRate",
        d."discount",
        get_items_with_wishlist_counts(d."itemId", $1, false) AS items
    FROM
        discounts d
    LEFT JOIN items i ON d."itemId" = i."itemId"
    LEFT JOIN categories c ON i."categoryId" = c.id
    WHERE
        d."startDate" <= $2
        AND d."endDate" >= $2' ||
    CASE
        WHEN _category_sector IS NOT NULL THEN
            ' AND c."categorySector" = $3'
        ELSE
            ''
    END ||
    ' ORDER BY d."discountRate" DESC'
    USING _user_id, _current_time_stamp, _category_sector;
END;
$function$
;

grant delete on table "public"."histories" to "anon";

grant insert on table "public"."histories" to "anon";

grant references on table "public"."histories" to "anon";

grant select on table "public"."histories" to "anon";

grant trigger on table "public"."histories" to "anon";

grant truncate on table "public"."histories" to "anon";

grant update on table "public"."histories" to "anon";

grant delete on table "public"."histories" to "authenticated";

grant insert on table "public"."histories" to "authenticated";

grant references on table "public"."histories" to "authenticated";

grant select on table "public"."histories" to "authenticated";

grant trigger on table "public"."histories" to "authenticated";

grant truncate on table "public"."histories" to "authenticated";

grant update on table "public"."histories" to "authenticated";

grant delete on table "public"."histories" to "service_role";

grant insert on table "public"."histories" to "service_role";

grant references on table "public"."histories" to "service_role";

grant select on table "public"."histories" to "service_role";

grant trigger on table "public"."histories" to "service_role";

grant truncate on table "public"."histories" to "service_role";

grant update on table "public"."histories" to "service_role";


